### ISSUE TITLE
Transcriptome for cfDNA run

### ISSUE THREAD

**Issue by TendoLiu** [grailbio/bio#1]
Hi, I wonder do I need any trancriptome file for cfDNA seq data? Since my data covers exons, so I am not sure if this package could analyze data like this.

Best wishes

**Comment by yipal** [comment]
Hi Tendo, can you explain what you're trying to do?  I don't believe any code in this repo is specific to cfDNA or exons, but it may still be useful to you.

**Comment by TendoLiu** [comment]
Hi yipal,
   Thanks for the quick reply. My case is pretty special. I have a interested gene X, and I designed probes to do target enrichment on the full sequence of this gene (promoter, exones, introns), the purpose is to capture any possible structural variation events associated with this gene (including gene fusions in introns and exones regions). Maybe I misunderstood, does the transcriptome file generated also include introns information? Because I assumed introns are not part of the transcriptome...

**Comment by yipal** [comment]
I see that you are trying to use bio-fusion. I'm afraid I am not familiar with that tool, but I'll try to find someone who is.

**Comment by TendoLiu** [comment]
Would appreciate it a lot.

**Comment by eksyang** [comment]
@TendoLiu Just to clarify, are you interested in the fusion occurred within this specific gene X, or this gene X with another gene Y somewhere else in the genome.

**Comment by TendoLiu** [comment]
Thanks. I would say both, but x-y fusion (intron/exon to intron/exon) would be a top interest.

**Comment by eksyang** [comment]
yes. you do need to include the transcriptome flag, but this file is no longer transcriptome but whole gene (https://github.com/grailbio/bio/blob/master/fusion/README.md, CfDNA dataset). Also, per your another thread, it is unclear to me what exactly files you used in the command line (those were represented by $transcriptome.) and do you have UMIs in the data etc.

**Comment by TendoLiu** [comment]
Thanks. The transcriptome file is now clear to me.
